title: zverok with ruby
email: zverok.offline@gmail.com
description: >
  @zverok. Ukrainian, Ruby programmer & poet.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: zverok
github_username:  zverok

# Build settings
markdown: kramdown
#kramdown:
  #input: GFM
  #syntax_highlighter: rouge
permalink: "/blog/:year-:month-:day-:title.html"

# plugins:
#   - jekyll-remote-theme

# remote_theme: swanson/lagom